apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ubgp8rk03-go 
  janus-idp.io/tekton: ubgp8rk03-go
  backstage.io/kubernetes-id: ubgp8rk03-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ubgp8rk03-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  