apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ubgp8rk03-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ubgp8rk03-go 
  name: ubgp8rk03-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ubgp8rk03-go 
